var Config = {
  NEW_ENGINEER_SHEET_NAME: 'New Engineer Responses',
  NEW_POTENTIAL_SITE_SHEET_NAME: 'New Potential Site Responses',
  NEW_RETAILER_SHEET_NAME: 'New Retailer Responses',
  NEW_CRM_SHEET_NAME: 'New CRM',
  EXISTING_ENGINEER_FORM_ID: '1a2b3c4d5e6f7g8h9i0j',
  EXISTING_POTENTIAL_SITE_FORM_ID: '16FOGBAvAS2ac85EaJuUARaQE60wEMAG5oA9Iz4xtA9g',
  EXISTING_RETAILER_FORM_ID: '1LBy0y-emr08r1ccJoOzuDe7oIw2VS4hUJGFi3s_0NHE'
};